### ISSUE TITLE
Configure Travis

### ISSUE THREAD

**Issue by noisy** [wise-team/steem-wise-core#40]
------
TODO:
- [x] - grant Travis access to steem-wise-core
- [x] - decide on semver versioning strategy
- [x] - implement semantic-release system
- [x] - write .travis.yml
   - [x] - building
   - [x] - unit testing
   - [x] - integration testing
   - [ ] - release
   - [x] - update steem-wise-core version in dependency repositories based on branches
- [x] - fix npm publish key error
- [x] - resolve collisions of concurrently run integration test (per branch ENVs that defines test account)

**Comment by Jblew** [comment]
Done.
